# Generated by Django 5.2.1 on 2025-05-09 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="student_id",
        ),
    ]
