# Generated by Django 5.2.1 on 2025-07-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitimage',
            name='image',
            field=models.URLField(),
        ),
    ]
